version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 1800
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      runas: root
